### ISSUE TITLE
Upgrading to Jena v3.17.0 issues with sparql-generate-jena v2.0.8

### ISSUE THREAD

**Issue by Pat-Carroll** [sparql-generate/sparql-generate#114]
Hello to the sparql-generate team,

My team and I have been using sparql-generate v2.0.0 in our project imported as a maven artifact, and we wanted to update to v2.0.8 so that we could resolve security issues with older versions of Apache Jena.

When looking at the github version tag for v2.0.8 I could see that the sparql-generate-jena project has been updated to v3.17.0 of Apache Jena, but while inspecting the jar delivered over Maven central for sparql-generate-jena v2.0.8, the apache jena version is still set to v3.13.0.  Are there remaining issues causing the migration to Jena v3.17.0 to fail for the publishing of the v2.0.8 artifacts? 

If so, I'd like to see if I could help with a pull request, but so far I was also having issues understanding how to clone the project and get it running in my IDE. Is there documentation available to get developers set up so they can make contributions to the project?

**Comment by maximelefrancois86** [comment]
OK thanks for the notice, the bug may be due to the `release-pom.xml` files that I just removed. Let  me try to publish a v2.0.9 with the migration to Jena v3.17.0.

About using SPARQL-Generate in your IDE, here is some steps you can follow for Eclipse:

* fork the project to your personal space or organisation
* clone the project 

```
git clone git@github.com:{your_organisation}/sparql-generate.git
``` 

* open the projects you need in Eclipse: File --> import --> Existing Maven Projects --> select the project(s) 
* define your run/debug configuration for some project, with some command line arguments

![image](https://user-images.githubusercontent.com/11416248/135647604-43bb6819-6490-4d3e-8035-d0840df12930.png)


Please let me know if the issue can be closed.

**Comment by Pat-Carroll** [comment]
Thank you for the quick reply.

The newly released version is working as expected with Jena v3.17.0.  For our project to close the security warning in Jena we will need to upgrade all the way to v4.2.0. After forcing this version of Jena in the build it looks like there are some newer changes to the Jena API which are causing some NoSuchMethodError in ParserSPARQLExt class.  

I will try to get the project running on Eclipse on my system and see if I can resolve those errors. In the meantime should I submit a separate issue ticket requesting an update to Jena v4.2.0?

**Comment by maximelefrancois86** [comment]
Hi, I expect the workload to be pretty high for updating to the new major version v4.x and I cannot commit on doing that any time soon. Any help will be welcome.
