### ISSUE TITLE
Difference between CSVStream and CSVMultipleOutput

### ISSUE THREAD

**Issue by lolive** [sparql-generate/sparql-generate#45]
What's the true difference between CSVMultipleOutput et CSVStream?

To me, only CSVStream is needed. Its second parameter is unneeded (why would anyone put a value different from 1?). But accepting the separator value as a parameter sounds like a no-brainer (cf issue #44).

Why did you develop two variants of CSV iterators?

**Comment by infomehdi** [comment]
The difference between `CSVMultipleOutput` and `CSVStream` is that `CSVStream` deals with large CSV datasets by streaming chunks of the CSV (batches) to Jena engine, instead of using `CSVMultipleOutput` that will have to read the whole CSV file before giving it to the engine.

As mentionned in the [Java documentation](https://ci.mines-stetienne.fr/sparql-generate/apidocs/index.html):
> For instance, binding variables to columns of a 14-column/1.500.000-rows CSV document takes a couple of minutes with CSVStream while iter:CSVMultipleOutput reaches java.lang.OutOfMemoryError: GC overhead limit exceeded.

In such case `CSVMultipleOutput` is not able to read a 14-column/1.500.000-rows CSV document, which  is why we support streaming values by dealing with big documents chunk-by-chunk (the number of rows per chunk is provided by the user in the second parameter).

**Comment by lolive** [comment]
After some code digging, I have discovered that CSVMultipleOutput accepts a string as the first parameter (containing the whole CSV document, loaded in memory).
