### ISSUE TITLE
Unable to access Documents for Iterator functions

### ISSUE THREAD

**Issue by ankushs92** [sparql-generate/sparql-generate#53]
This link :

https://ci.mines-stetienne.fr/sparql-generate/functions.html

**Comment by maximelefrancois86** [comment]
Thanks for spotting this broken link. Where is it located ?

This page was deleted because its content is actually duplicated here:

- https://ci.mines-stetienne.fr/sparql-generate/playground.html#ex=example/generate/01-Functions
- https://ci.mines-stetienne.fr/sparql-generate/playground.html#ex=example/generate/03-Iterators

The complete documentation of the functions is here :

- http://w3id.org/sparql-generate/fn/

The complete documentation of the iterators is here: 

- http://w3id.org/sparql-generate/iter/

**Comment by ankushs92** [comment]
The link is broken on the home page : https://ci.mines-stetienne.fr/sparql-generate/

Look for " our predefined SPARQL binding functions and SPARQL-Generate iterator functions"

**Comment by maximelefrancois86** [comment]
Ok thanks, will fix this.
